const books=[
{volume:"Volume One",title:"The Pleasure of Learning and the Joy of Knowing",image:"assets/books/pleasure.jpg",tagline:"Learn deeply. Think freely. Know truly.",blurb:"A meditation on curiosity as a way of life—why learning, pursued honestly and without pretense, becomes its own reward and the surest path to a settled mind.",note:"On the other side stands the person who measures everything by utility and wealth, and mocks what cannot be priced."},
{volume:"Volume Two",title:"Prophet Muhammad’s Narratives for Exceptional Minds",image:"assets/books/prophet.jpg",tagline:"Character as the purpose of revelation.",blurb:"A scholarly gathering of Prophetic narrations for readers seeking genuine intellectual and moral refinement.",note:"Built on Prophetic vision and curiosity, and on the transmission of Hazrat Ali—the Gate of the city of wisdom and knowledge."},
{volume:"Volume Three",title:"We Are One Family Under God",image:"assets/books/family.jpg",tagline:"Different paths, one destination: love.",blurb:"An interfaith call to cordiality, placing scripture beside scripture to argue that every tradition, read rightly, asks us to welcome the stranger and value one another.",note:"I was a stranger and you welcomed me. — Jesus Christ"},
{volume:"Volume Four",title:"The Essence of Existence",image:"assets/books/essence.jpg",tagline:"Beyond perception. Beyond time. The truth within.",blurb:"A Sufi-philosophical inquiry into being itself—what remains when perception, time, and appearance fall away.",note:"The volume in which his motto becomes a method: to see things as they truly are."},
{volume:"Volume Five",title:"My Mind Works as a Pressure Cooker",image:"assets/books/pressure.jpg",tagline:"Understand. Express. Heal.",blurb:"A candid, deeply human look at the mind under pressure—and a gentle argument for release, reflection, and renewal before it all overflows.",note:"Fatimi finds the condition named in the Qur’an itself: بَاخِع—one who would destroy himself with grief."},
{volume:"Volume Six",title:"The Uncharted Realm of Knowledge and Wisdom",image:"assets/books/uncharted.jpg",tagline:"Beyond the maps. Beyond the known.",blurb:"The capstone of the collection—an invitation past settled knowledge into a realm bounded not by borders, but by understanding.",note:"A journey of the soul, a quest of the mind, and a legacy for generations."}];
let active=0;const $=id=>document.getElementById(id);const dots=books.map((book,index)=>{const dot=document.createElement("button");dot.setAttribute("role","tab");dot.setAttribute("aria-label",`Show ${book.volume}`);dot.onclick=()=>show(index);$("bookDots").append(dot);return dot});
function show(index){active=(index+books.length)%books.length;const b=books[active];$("bookCover").src=b.image;$("bookCover").alt=`Cover of ${b.title}`;$("bookVolume").textContent=b.volume;$("bookTitle").textContent=b.title;$("bookTagline").textContent=b.tagline;$("bookBlurb").textContent=b.blurb;$("bookNote").textContent=b.note;dots.forEach((d,i)=>{d.classList.toggle("active",i===active);d.setAttribute("aria-selected",i===active)})}
$("previousBook").onclick=()=>show(active-1);$("nextBook").onclick=()=>show(active+1);$("year").textContent=new Date().getFullYear();show(0);setInterval(()=>show(active+1),7000);
